"""
Mock vLLM OpenAI-Compatible Server for Local Testing

This mock implements the OpenAI API endpoints that vLLM provides,
allowing testing of the auth transformer stack without requiring
a GPU or actual model inference.

Implements:
- GET /health - Health check
- GET /v1/models - List models
- POST /v1/chat/completions - Chat completions (streaming and non-streaming)
- POST /v1/completions - Text completions

The responses are pre-canned but realistic, allowing full end-to-end
testing of the auth transformer pipeline.
"""

import asyncio
import json
import logging
import os
import time
import uuid
from typing import Any, Dict, List, Optional

import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Configuration
MODEL_NAME = os.getenv("MODEL_NAME", "smollm-360m")
RESPONSE_DELAY_MS = int(os.getenv("RESPONSE_DELAY_MS", "50"))

app = FastAPI(title="Mock vLLM Server", version="1.0.0")


# =============================================================================
# Models
# =============================================================================

class ChatMessage(BaseModel):
    role: str
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.7
    top_p: Optional[float] = 1.0
    n: Optional[int] = 1
    stream: Optional[bool] = False
    max_tokens: Optional[int] = 100
    presence_penalty: Optional[float] = 0
    frequency_penalty: Optional[float] = 0
    user: Optional[str] = None


class CompletionRequest(BaseModel):
    model: str
    prompt: str
    max_tokens: Optional[int] = 100
    temperature: Optional[float] = 0.7
    top_p: Optional[float] = 1.0
    n: Optional[int] = 1
    stream: Optional[bool] = False
    echo: Optional[bool] = False


class Usage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class Choice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: str


class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[Choice]
    usage: Usage


class ModelInfo(BaseModel):
    id: str
    object: str = "model"
    created: int
    owned_by: str = "vllm"


class ModelsResponse(BaseModel):
    object: str = "list"
    data: List[ModelInfo]


# =============================================================================
# Mock Response Generator
# =============================================================================

# Pre-defined responses based on keywords in the prompt
MOCK_RESPONSES = {
    "hello": "Hello! I'm a mock AI assistant running in the SmolLM-360M test environment. How can I help you today?",
    "machine learning": "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. It focuses on developing algorithms that can access data and use it to learn for themselves.",
    "gravity": "Gravity is a fundamental force of nature that attracts objects with mass toward each other. On Earth, it gives weight to physical objects and causes things to fall toward the ground when dropped.",
    "python": "Python is a high-level, interpreted programming language known for its readability and versatility. It's widely used in web development, data science, artificial intelligence, and automation.",
    "test": "This is a test response from the mock vLLM server. The auth transformer pipeline is working correctly!",
    "default": "I am a mock language model response. This response is generated by a test stub to validate the auth transformer and inference pipeline without requiring an actual GPU or model."
}


def get_mock_response(messages: List[ChatMessage]) -> str:
    """Generate a mock response based on the input messages."""
    # Get the last user message
    user_messages = [m for m in messages if m.role == "user"]
    if not user_messages:
        return MOCK_RESPONSES["default"]
    
    last_message = user_messages[-1].content.lower()
    
    # Check for keywords
    for keyword, response in MOCK_RESPONSES.items():
        if keyword in last_message:
            return response
    
    return MOCK_RESPONSES["default"]


def count_tokens(text: str) -> int:
    """Approximate token count (roughly 4 chars per token)."""
    return max(1, len(text) // 4)


# =============================================================================
# Endpoints
# =============================================================================

@app.get("/health")
async def health():
    """Health check endpoint (vLLM compatible)."""
    return {"status": "healthy"}


@app.get("/v1/models")
async def list_models():
    """List available models (OpenAI API compatible)."""
    return ModelsResponse(
        data=[
            ModelInfo(
                id=MODEL_NAME,
                created=int(time.time()) - 86400,  # Created "yesterday"
            )
        ]
    )


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """
    Chat completions endpoint (OpenAI API compatible).
    
    Supports both streaming and non-streaming responses.
    """
    logger.info(f"Chat completion request: model={request.model}, stream={request.stream}")
    
    # Generate mock response
    response_text = get_mock_response(request.messages)
    
    # Truncate to max_tokens (approximate)
    if request.max_tokens:
        words = response_text.split()
        max_words = request.max_tokens // 2  # Rough estimate
        if len(words) > max_words:
            response_text = " ".join(words[:max_words]) + "..."
    
    completion_id = f"chatcmpl-{uuid.uuid4().hex[:8]}"
    created = int(time.time())
    
    if request.stream:
        # Streaming response
        async def generate_stream():
            # First chunk with role
            first_chunk = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": request.model,
                "choices": [{
                    "index": 0,
                    "delta": {"role": "assistant"},
                    "finish_reason": None
                }]
            }
            yield f"data: {json.dumps(first_chunk)}\n\n"
            
            # Stream content word by word
            words = response_text.split()
            for i, word in enumerate(words):
                # Add space before word (except first)
                content = word if i == 0 else " " + word
                
                chunk = {
                    "id": completion_id,
                    "object": "chat.completion.chunk",
                    "created": created,
                    "model": request.model,
                    "choices": [{
                        "index": 0,
                        "delta": {"content": content},
                        "finish_reason": None
                    }]
                }
                yield f"data: {json.dumps(chunk)}\n\n"
                
                # Simulate token generation delay
                await asyncio.sleep(RESPONSE_DELAY_MS / 1000)
            
            # Final chunk with finish_reason
            final_chunk = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": request.model,
                "choices": [{
                    "index": 0,
                    "delta": {},
                    "finish_reason": "stop"
                }]
            }
            yield f"data: {json.dumps(final_chunk)}\n\n"
            yield "data: [DONE]\n\n"
        
        return StreamingResponse(
            generate_stream(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            }
        )
    
    else:
        # Non-streaming response
        # Add a small delay to simulate inference
        await asyncio.sleep(0.1)
        
        prompt_tokens = sum(count_tokens(m.content) for m in request.messages)
        completion_tokens = count_tokens(response_text)
        
        return ChatCompletionResponse(
            id=completion_id,
            created=created,
            model=request.model,
            choices=[
                Choice(
                    index=0,
                    message=ChatMessage(role="assistant", content=response_text),
                    finish_reason="stop"
                )
            ],
            usage=Usage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens
            )
        )


@app.post("/v1/completions")
async def completions(request: CompletionRequest):
    """
    Text completions endpoint (OpenAI API compatible).
    
    This is the older completion API, less commonly used with chat models.
    """
    logger.info(f"Completion request: model={request.model}")
    
    completion_id = f"cmpl-{uuid.uuid4().hex[:8]}"
    created = int(time.time())
    
    # Simple continuation of the prompt
    response_text = f" This is a mock completion response to: '{request.prompt[:50]}...'"
    
    await asyncio.sleep(0.1)
    
    return {
        "id": completion_id,
        "object": "text_completion",
        "created": created,
        "model": request.model,
        "choices": [{
            "text": response_text,
            "index": 0,
            "logprobs": None,
            "finish_reason": "stop"
        }],
        "usage": {
            "prompt_tokens": count_tokens(request.prompt),
            "completion_tokens": count_tokens(response_text),
            "total_tokens": count_tokens(request.prompt) + count_tokens(response_text)
        }
    }


@app.get("/ready")
async def ready():
    """Readiness check endpoint."""
    return {"status": "ready"}


if __name__ == "__main__":
    port = int(os.getenv("PORT", "8000"))
    logger.info(f"Starting Mock vLLM server on port {port}")
    logger.info(f"Serving model: {MODEL_NAME}")
    uvicorn.run(app, host="0.0.0.0", port=port)
