apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-inference

resources:
  - namespace.yaml
  - storage-class.yaml
  - external-services-configmap.yaml
  - external-service-stubs-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ml-inference-platform
  app.kubernetes.io/managed-by: kustomize
