apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-inference

resources:
  - pvc.yaml
  - inference-service.yaml

commonLabels:
  app: smollm-360m
  model-type: llm
  app.kubernetes.io/part-of: ml-inference-platform
